"""rewrited regression model

Revision ID: 27ea6366ba95
Revises: 1277451be81b
Create Date: 2025-06-17 16:02:57.558943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ea6366ba95'
down_revision: Union[str, None] = '1277451be81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_models', sa.Column('adj_r_squared', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('f_statistic', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('f_p_value', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('n_observations', sa.Integer(), nullable=True))
    op.add_column('regression_models', sa.Column('filters', sa.JSON(), nullable=False))
    op.add_column('regression_models', sa.Column('formula', sa.String(), nullable=False))
    op.drop_constraint(op.f('regression_models_platform_id_fkey'), 'regression_models', type_='foreignkey')
    op.drop_column('regression_models', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_models', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('regression_models_platform_id_fkey'), 'regression_models', 'car_platforms', ['platform_id'], ['id'], ondelete='CASCADE')
    op.drop_column('regression_models', 'formula')
    op.drop_column('regression_models', 'filters')
    op.drop_column('regression_models', 'n_observations')
    op.drop_column('regression_models', 'f_p_value')
    op.drop_column('regression_models', 'f_statistic')
    op.drop_column('regression_models', 'adj_r_squared')
    # ### end Alembic commands ###
