"""initial

Revision ID: 5e027df5d85d
Revises: 
Create Date: 2025-06-11 20:03:33.996375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e027df5d85d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_search_url', sa.String(), nullable=False),
    sa.Column('brand_selector', sa.String(), nullable=False),
    sa.Column('brand_item_selector', sa.String(), nullable=True),
    sa.Column('model_selector', sa.String(), nullable=False),
    sa.Column('model_item_selector', sa.String(), nullable=True),
    sa.Column('year_from_selector', sa.String(), nullable=False),
    sa.Column('year_from_item_selector', sa.String(), nullable=True),
    sa.Column('year_to_selector', sa.String(), nullable=False),
    sa.Column('year_to_item_selector', sa.String(), nullable=True),
    sa.Column('button_selector', sa.String(), nullable=True),
    sa.Column('car_list_selector', sa.String(), nullable=False),
    sa.Column('url_to_details', sa.String(), nullable=False),
    sa.Column('close_selector', sa.String(), nullable=True),
    sa.Column('year_bs4_selector', sa.String(), nullable=False),
    sa.Column('price_bs4_selector', sa.String(), nullable=False),
    sa.Column('mileage_bs4_selector', sa.String(), nullable=False),
    sa.Column('views_bs4_selector', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=False),
    sa.Column('year_to', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_platform_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('scraped_url', sa.String(), nullable=True),
    sa.Column('search_position', sa.Integer(), nullable=True),
    sa.Column('scraped_year', sa.Integer(), nullable=True),
    sa.Column('scraped_price', sa.Integer(), nullable=True),
    sa.Column('scraped_currency', sa.String(length=3), nullable=True),
    sa.Column('scraped_mileage', sa.Integer(), nullable=True),
    sa.Column('scraped_mileage_unit', sa.String(length=10), nullable=True),
    sa.Column('scraped_number_of_views', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_platform_id'], ['car_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['scrape_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_cars')
    op.drop_table('scrape_requests')
    op.drop_table('cars')
    op.drop_table('car_platforms')
    # ### end Alembic commands ###
